import { Sortable, MultiDrag } from 'sortablejs';

Sortable.mount(new MultiDrag());

window.Vaadin.Flow.sortableConnector = {
    initLazy: function (customConfig, c, layout) {
        // Check whether the connector was already initialized
        if (c.$connector) {
            return;
        }

        c.$connector = {
            //// functions
            setOption : function(optionName, optionValue) {
                this.sortable.options[optionName] = optionValue;
            }
        };

        c.$connector.sortable = Sortable.create(layout, customConfig);

        c.$connector.sortable.options.onEnd = function (/**Event*/evt) {
            let oldIndexes = [evt.oldIndex];
            let newIndexes = [evt.newIndex];
            if (evt.newIndicies && evt.oldIndicies && evt.newIndicies.length > 0) {
                newIndexes = evt.newIndicies.map(newIndex => newIndex.index);
                oldIndexes = evt.oldIndicies.map(oldIndex => oldIndex.index);
            }
            if (evt.to === evt.from) {
                c.$server.onReorderListener(oldIndexes, newIndexes);
            } else {
                const clone = (evt.pullMode === 'clone');
                evt.from.parentElement.$server.onRemoveListener(oldIndexes, clone);
                evt.to.parentElement.$server.onAddListener(newIndexes, clone);
                if (clone) {
                    // remove the clone generated by the client-side
                    if (evt.clone) {
                        evt.clone.parentNode.removeChild(evt.clone);
                    } else {
                        // multidrag
                        evt.clones.forEach(clone => clone.parentNode.removeChild(clone));
                    }
                }

            }
        }

        c.$connector.sortable.options.onChoose = function (/**Event*/evt) {
            c.dispatchEvent(new CustomEvent('on-choose'));
        }

        c.$connector.sortable.options.onUnchoose = function (/**Event*/evt) {
            c.dispatchEvent(new CustomEvent('on-unchoose'));
        }
        c.$connector.sortable.options.onChange = function (/**Event*/evt) {
            c.dispatchEvent(new CustomEvent('on-change'));
        }
    }
}